project_id = "zljgjxiwoedzwbmgeivd"

[functions.ai-task-suggestions]
verify_jwt = true

[functions.ai-habit-recommendations]
verify_jwt = true

[functions.ai-productivity-insights]
verify_jwt = true

[functions.send-task-reminder]
verify_jwt = false